### ISSUE TITLE
Error: The requested accessory 'GPIODevice' was not registered by any plugin.

### ISSUE THREAD

**Issue by clrmsc** [Paulraita/homebridge-relays#6]
Hi Guys don't work, pls help.
Error loading accessory requested in your config.json at position 1
Error: The requested accessory 'GPIODevice' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)

**Comment by clrmsc** [comment]
My way to fix this problem, install steps:
_update pi_
sudo apt-get update && sudo apt-get upgrade -y

_homebridge_
sudo apt install git
git clone https://github.com/fantomnotabene/homebridge_setup_script
cd homebridge_setup_script
bash install.sh

_plugin_
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
sudo apt install nodejs

cd /tmp
wget https://unicorn.drogon.net/wiringpi-2.46-1.deb
sudo dpkg -i wiringpi-2.46-1.deb

sudo usermod -a -G gpio pi
sudo npm install -g homebridge-gpio-device --unsafe-perm

**Comment by lycheeEng** [comment]
Same problem here, I'll try your steps at another time.

This is my error log:
![Screenshot 2020-07-11 at 10 11 52 PM](https://user-images.githubusercontent.com/12211144/87226043-c20ea480-c3c3-11ea-8968-bf0f341c5036.png)
![Screenshot 2020-07-11 at 10 12 00 PM](https://user-images.githubusercontent.com/12211144/87226045-c3d86800-c3c3-11ea-8f9f-c96c112d5c83.png)
